name:  Ci/Cd Pipeline 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 
    

jobs:
  build:

    runs-on: self-hosted
    
    strategy:
      matrix: 
        node-version: [14.x]
        
    
    steps:
    - name: cleanup 
      run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE
    - uses: actions/checkout@v3
    - run: sudo npm i 
    - run: sudo pm2 kill -a
    - run: sudo pm2 start index.js 
